# Generated by Django 4.2.19 on 2025-06-17 13:56
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'analytics',
            '0002_remove_processeds3log_analytics_processeds3log_unique_name_embargoed_and_more',
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='processeds3log',
            name='analytics_processeds3log_unique_name_embargoed',
        ),
        migrations.AddField(
            model_name='processeds3log',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='processeds3log',
            constraint=models.UniqueConstraint(
                fields=('name', 'private', 'historically_embargoed'),
                name='analytics_processeds3log_unique_name_embargoed',
            ),
        ),
    ]
