# Generated by Django 4.2.19 on 2025-06-18 20:05
from __future__ import annotations

import django.contrib.postgres.indexes
import django.core.validators
from django.db import migrations, models
import django_extensions.db.fields

import dandiapi.api.storage


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0021_stagingapplication_allowed_origins_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateAssetBlob',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                ('embargoed', models.BooleanField(default=False)),
                ('blob_id', models.UUIDField(unique=True)),
                (
                    'sha256',
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=64,
                        null=True,
                        validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')],
                    ),
                ),
                (
                    'etag',
                    models.CharField(
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator('^[0-9a-f]{32}(-[1-9][0-9]*)?$')
                        ],
                    ),
                ),
                ('size', models.PositiveBigIntegerField()),
                ('download_count', models.PositiveBigIntegerField(default=0)),
                (
                    'blob',
                    models.FileField(
                        blank=True,
                        storage=dandiapi.api.storage.get_private_storage,
                        upload_to=dandiapi.api.storage.get_storage_prefix,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='AssetBlob',
            new_name='PublicAssetBlob',
        ),
        migrations.RenameIndex(
            model_name='publicassetblob',
            new_name='api_publica_etag_762c43_hash',
            old_name='api_assetbl_etag_cf8377_hash',
        ),
        migrations.AddIndex(
            model_name='privateassetblob',
            index=django.contrib.postgres.indexes.HashIndex(
                fields=['etag'], name='api_private_etag_0c1f0a_hash'
            ),
        ),
        migrations.AddConstraint(
            model_name='privateassetblob',
            constraint=models.UniqueConstraint(
                fields=('etag', 'size'), name='unique-private-etag-size'
            ),
        ),
    ]
