# Generated by Django 4.2.19 on 2025-06-18 15:39
from __future__ import annotations

from django.db import migrations, models

import dandiapi.api.storage


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0021_stagingapplication_allowed_origins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetblob',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assetblob',
            name='blob',
            field=models.FileField(
                blank=True,
                storage=dandiapi.api.storage.get_storage,
                upload_to=dandiapi.api.storage.get_storage_prefix,
            ),
        ),
    ]
