# Generated by Django 4.2.19 on 2025-06-18 20:06
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0022_privateassetblob_rename_assetblob_publicassetblob_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asset',
            name='blob-xor-zarr',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='blob',
            new_name='public_blob',
        ),
        migrations.AddField(
            model_name='asset',
            name='private_blob',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='assets',
                to='api.privateassetblob',
            ),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ('private_blob__isnull', True),
                        ('public_blob__isnull', True),
                        ('zarr__isnull', False),
                    ),
                    models.Q(
                        ('private_blob__isnull', False),
                        ('public_blob__isnull', True),
                        ('zarr__isnull', True),
                    ),
                    models.Q(
                        ('private_blob__isnull', True),
                        ('public_blob__isnull', False),
                        ('zarr__isnull', True),
                    ),
                    _connector='OR',
                ),
                name='public-blob-xor-private-blob-xor-zarr',
            ),
        ),
    ]
