# Generated by Django 4.2.19 on 2025-06-23 20:25
from __future__ import annotations

import uuid

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields

import dandiapi.api.storage


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0023_remove_asset_blob_xor_zarr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateUpload',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('embargoed', models.BooleanField(default=False)),
                ('upload_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                (
                    'etag',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=40,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator('^[0-9a-f]{32}(-[1-9][0-9]*)?$')
                        ],
                    ),
                ),
                (
                    'multipart_upload_id',
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ('size', models.PositiveBigIntegerField()),
                (
                    'blob',
                    models.FileField(
                        blank=True,
                        storage=dandiapi.api.storage.get_private_storage,
                        upload_to=dandiapi.api.storage.get_storage_prefix,
                    ),
                ),
            ],
            options={
                'ordering': ['created'],
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Upload',
            new_name='PublicUpload',
        ),
        migrations.RenameIndex(
            model_name='publicupload',
            new_name='api_publicu_etag_8ef2c0_idx',
            old_name='api_upload_etag_a467fd_idx',
        ),
        migrations.AddField(
            model_name='privateupload',
            name='dandiset',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='private_uploads',
                to='api.dandiset',
            ),
        ),
        migrations.AddIndex(
            model_name='privateupload',
            index=models.Index(fields=['etag'], name='api_private_etag_a17502_idx'),
        ),
    ]
